const db = require('./models');

const products = [
  {
    name: 'angelica',
    image: 'oil_angelica_5_ml.jpg',
    description: 'description',
    size: 5,
    measure: 'ml',
    price: 15.88,
    category: 'essentialOil',
    details: 'Reduces the wrinkles, increases skin firmness.',
  },
  {
    name: 'eucaliptus_blue',
    image: 'oil_eulyptusBlue_15_ml.jpg',
    description: 'description',
    size: 15,
    measure: 'ml',
    price: 16.45,
    category: 'essentialOil',
    details: 'Reduces the wrinkles, increases skin firmness.',
  },
  {
    name: 'grapefruit',
    image: 'oil_grapefruit_15_ml.jpg',
    description: 'description',
    size: 15,
    measure: 'ml',
    price: 17.25,
    category: 'essentialOil',
    details: 'Reduces the wrinkles, increases skin firmness.',
  },
  {
    name: 'jade_lemon',
    image: 'oil_jadeLemon_5_ml.jpg',
    description: 'description',
    size: 5,
    measure: 'ml',
    price: 18.33,
    category: 'essentialOil',
    details: 'Reduces the wrinkles, increases skin firmness.',
  },
  {
    name: 'lavender',
    image: 'oil_lavender_15_ml.jpg',
    description: 'description',
    size: 15,
    measure: 'ml',
    price: 22.44,
    category: 'essentialOil',
    details: 'Reduces the wrinkles, increases skin firmness.',
  },
  {
    name: 'spearmint',
    image: 'oil_spearmint_15_ml.jpg',
    description: 'description',
    size: 15,
    measure: 'ml',
    price: 12.33,
    category: 'essentialOil',
    details: 'Reduces the wrinkles, increases skin firmness.',
  },
  {
    name: 'evening_peace',
    image: 'bodyCare_eveningPeace_236_ml.jpg',
    description: 'description',
    size: 236,
    measure: 'ml',
    price: 23.65,
    category: 'bodyCare',
    details: 'shower gel.',
  },
  {
    name: 'morning_start',
    image: 'bodyCare_morningStart_236_ml.jpg',
    description: 'description',
    size: 236,
    measure: 'ml',
    price: 23.69,
    category: 'bodyCare',
    details: 'shower gel.',
  },
  {
    name: 'sensation',
    image: 'bodyCare_sensation_236_ml.jpg',
    description: 'description',
    size: 236,
    measure: 'ml',
    price: 23.69,
    category: 'bodyCare',
    details: 'shower gel.',
  },
  {
    name: 'dragon_time',
    image: 'bodyCare_dragonTime_236_ml.jpg',
    description: 'description',
    size: 236,
    measure: 'ml',
    price: 23.69,
    category: 'bodyCare',
    details: 'shower gel.',
  },
  {
    name: 'bath_and_shower',
    image: 'bodyCare_bathAndShower_236_ml.jpg',
    description: 'description',
    size: 236,
    measure: 'ml',
    price: 23.69,
    category: 'bodyCare',
    details: 'shower gel.',
  },

  {
    name: 'aria',
    image: 'difuser_aria_eu.jpg',
    description: 'description',
    size: 180,
    measure: 'ml',
    price: 150.44,
    category: 'difuser',
    details: 'Reduces the wrinkles, increases skin firmness.',
  },
  {
    name: 'aroma_globe',
    image: 'difuser_aromaGlobe_eu.jpg',
    description: 'description',
    size: 285,
    measure: 'ml',
    price: 111.55,
    category: 'difuser',
    details: 'Reduces the wrinkles, increases skin firmness.',
  },
  {
    name: 'dewdrop',
    image: 'difuser_dewdrop_eu.jpg',
    description: 'description',
    size: 285,
    measure: 'ml',
    price: 111.55,
    category: 'difuser',
    details: 'Reduces the wrinkles, increases skin firmness.',
  },
  {
    name: 'feather_the_owl',
    image: 'difuser_featherTheOwl_eu.jpg',
    description: 'description',
    size: 285,
    measure: 'ml',
    price: 111.55,
    category: 'difuser',
    details: 'Reduces the wrinkles, increases skin firmness.',
  },
  {
    name: 'haven',
    image: 'difuser_haven_eu.jpg',
    description: 'description',
    size: 285,
    measure: 'ml',
    price: 111.55,
    category: 'difuser',
    details: 'Reduces the wrinkles, increases skin firmness.',
  },
  {
    name: 'lantern',
    image: 'difuser_lantern_eu.jpg',
    description: 'description',
    size: 285,
    measure: 'ml',
    price: 111.55,
    category: 'difuser',
    details: 'Reduces the wrinkles, increases skin firmness.',
  },
  {
    name: 'sweet_aroma',
    image: 'difuser_sweetAroma_eu.jpg',
    description: 'description',
    size: 285,
    measure: 'ml',
    price: 111.55,
    category: 'difuser',
    details: 'Reduces the wrinkles, increases skin firmness.',
  },
  {
    name: 'dragon_time',
    image: 'oilMassage_dragonTime_236_ml.jpg',
    description: 'Vegetable Oil for Woman',
    size: 236,
    measure: 'ml',
    price: 35.48,
    category: 'massageOil',
    details: 'Vegetable Oil for Woman.',
  },
  {
    name: 'v-6',
    image: 'oilMassage_v-6_944_ml.jpg',
    description: 'Enhanced Vegetable Oil Refill',
    size: 944,
    measure: 'ml',
    price: 35.48,
    category: 'massageOil',
    details: 'Reduces the wrinkles, increases skin firmness.',
  },

  {
    name: 'relaxation',
    image: 'oilMassage_relaxation_236_ml.jpg',
    description: 'Vitality enhancer Vegetable Oil',
    size: 236,
    measure: 'ml',
    price: 35.48,
    category: 'massageOil',
    details: 'Reduces stress.',
  },
  {
    name: 'sensation',
    image: 'oilMassage_sensation_236_ml.jpg',
    description: 'Sense enhancer Vegetable Oil',
    size: 236,
    measure: 'ml',
    price: 35.48,
    category: 'massageOil',
    details: 'Reduces stress.',
  },
  {
    name: 'cel-lite_magic',
    image: 'oilMassage_cel-liteMagic_236_ml.jpg',
    description: 'Sking structure enhancer Vegetable Oil',
    size: 236,
    measure: 'ml',
    price: 35.48,
    category: 'massageOil',
    details: 'Reduces stress.',
  },

  {
    name: 'roll1',
    image: 'roll1.png',
    description: 'description',
    size: 15,
    measure: 'ml',
    price: 18.78,
    category: 'roll',
    details: 'Reduces the wrinkles, increases skin firmness.',
  },
  {
    name: 'roll2',
    image: 'roll2.png',
    description: 'description',
    size: 15,
    measure: 'ml',
    price: 25.55,
    category: 'roll',
    details: 'Reduces the wrinkles, increases skin firmness.',
  },
  {
    name: 'roll3',
    image: 'roll3.png',
    description: 'description',
    size: 15,
    measure: 'ml',
    price: 12.33,
    category: 'roll',
    details: 'Reduces the wrinkles, increases skin firmness.',
  },
  {
    name: 'roll4',
    image: 'roll4.png',
    description: 'description',
    size: 15,
    measure: 'ml',
    price: 28.84,
    category: 'roll',
    details: 'Reduces the wrinkles, increases skin firmness.',
  },
];

async function seed() {
  try {
    await db.sequelize.sync({ force: true });

    await Promise.all(
      products.map((product) => {
        return db.product.create(product);
      })
    );

    console.log('Database seeded!');
    process.exit(0);
  } catch (err) {
    console.error(err);
    process.exit(1);
  }
}

seed();
