const db = require('./models');

const products = [
  {
    name: 'essentialoil1',
    image: 'essentialOil1.png',
    description: 'description',
    size: 15,
    measure: 'ml',
    price: 15.88,
    category: 'essentialOil',
    details: 'Reduces the wrinkles, increases skin firmness.',
  },
  {
    name: 'essentialoil2',
    image: 'essentialOil2.png',
    description: 'description',
    size: 14,
    measure: 'ml',
    price: 16.45,
    category: 'essentialOil',
    details: 'Reduces the wrinkles, increases skin firmness.',
  },
  {
    name: 'essentialoil3',
    image: 'essentialOil3.png',
    description: 'description',
    size: 17,
    measure: 'ml',
    price: 17.25,
    category: 'essentialOil',
    details: 'Reduces the wrinkles, increases skin firmness.',
  },
  {
    name: 'essentialoil4',
    image: 'essentialOil4.png',
    description: 'description',
    size: 15,
    measure: 'ml',
    price: 18.33,
    category: 'essentialOil',
    details: 'Reduces the wrinkles, increases skin firmness.',
  },
  {
    name: 'bodyCare1',
    image: 'bodyCare1.png',
    description: 'description',
    size: 150,
    measure: 'ml',
    price: 22.44,
    category: 'bodyCare',
    details: 'Reduces the wrinkles, increases skin firmness.',
  },
  {
    name: 'bodyCare2',
    image: 'bodyCare2.png',
    description: 'description',
    size: 180,
    measure: 'ml',
    price: 23.65,
    category: 'bodyCare',
    details: 'Reduces the wrinkles, increases skin firmness.',
  },
  {
    name: 'bodyCare3',
    image: 'bodyCare3.png',
    description: 'description',
    size: 200,
    measure: 'ml',
    price: 24.74,
    category: 'bodyCare',
    details: 'Reduces the wrinkles, increases skin firmness.',
  },
  {
    name: 'bodyCare4',
    image: 'bodyCare4.png',
    description: 'description',
    size: 150,
    measure: 'ml',
    price: 17.22,
    category: 'bodyCare',
    details: 'Reduces the wrinkles, increases skin firmness.',
  },
  {
    name: 'bodyCare5',
    image: 'bodyCare5.png',
    description: 'description',
    size: 185,
    measure: 'ml',
    price: 24.21,
    category: 'bodyCare',
    details: 'Reduces the wrinkles, increases skin firmness.',
  },
  {
    name: 'difuser1',
    image: 'difuser1.png',
    description: 'description',
    size: 180,
    measure: 'ml',
    price: 150.44,
    category: 'difuser',
    details: 'Reduces the wrinkles, increases skin firmness.',
  },
  {
    name: 'difuser2',
    image: 'difuser2.png',
    description: 'description',
    size: 285,
    measure: 'ml',
    price: 111.55,
    category: 'difuser',
    details: 'Reduces the wrinkles, increases skin firmness.',
  },
  {
    name: 'difuser3',
    image: 'difuser3.png',
    description: 'description',
    size: 185,
    measure: 'ml',
    price: 132.33,
    category: 'difuser',
    details: 'Reduces the wrinkles, increases skin firmness.',
  },
  {
    name: 'difuser4',
    image: 'difuser4.png',
    description: 'description',
    size: 210,
    measure: 'ml',
    price: 90.55,
    category: 'difuser',
    details: 'Reduces the wrinkles, increases skin firmness.',
  },
  {
    name: 'difuser5',
    image: 'difuser5.png',
    description: 'description',
    size: 155,
    measure: 'ml',
    price: 80.22,
    category: 'difuser',
    details: 'Reduces the wrinkles, increases skin firmness.',
  },
  {
    name: 'hairCare1',
    image: 'hairCare1.png',
    description: 'description',
    size: 255,
    measure: 'ml',
    price: 15.12,
    category: 'hairCare',
    details: 'Reduces the wrinkles, increases skin firmness.',
  },
  {
    name: 'hairCare2',
    image: 'hairCare2.png',
    description: 'description',
    size: 255,
    measure: 'ml',
    price: 19.21,
    category: 'hairCare',
    details: 'Reduces the wrinkles, increases skin firmness.',
  },
  {
    name: 'hairCare3',
    image: 'hairCare3.png',
    description: 'description',
    size: 255,
    measure: 'ml',
    price: 15.12,
    category: 'hairCare',
    details: 'Reduces the wrinkles, increases skin firmness.',
  },
  {
    name: 'hairCare4',
    image: 'hairCare4.png',
    description: 'description',
    size: 255,
    measure: 'ml',
    price: 22.55,
    category: 'hairCare',
    details: 'Reduces the wrinkles, increases skin firmness.',
  },
  {
    name: 'hairCare5',
    image: 'hairCare5.png',
    description: 'description',
    size: 255,
    measure: 'ml',
    price: 22.55,
    category: 'hairCare',
    details: 'Reduces the wrinkles, increases skin firmness.',
  },

  {
    name: 'massageOil1',
    image: 'massageOil1.png',
    description: 'description',
    size: 155,
    measure: 'ml',
    price: 35.48,
    category: 'massageOil',
    details: 'Reduces the wrinkles, increases skin firmness.',
  },
  {
    name: 'massageOil2',
    image: 'massageOil2.png',
    description: 'description',
    size: 125,
    measure: 'ml',
    price: 44.66,
    category: 'massageOil',
    details: 'Reduces the wrinkles, increases skin firmness.',
  },
  {
    name: 'massageOil3',
    image: 'massageOil3.png',
    description: 'description',
    size: 145,
    measure: 'ml',
    price: 24.21,
    category: 'massageOil',
    details: 'Reduces the wrinkles, increases skin firmness.',
  },
  {
    name: 'massageOil4',
    image: 'massageOil4.png',
    description: 'description',
    size: 165,
    measure: 'ml',
    price: 28.78,
    category: 'massageOil',
    details: 'Reduces the wrinkles, increases skin firmness.',
  },

  {
    name: 'roll1',
    image: 'roll1.png',
    description: 'description',
    size: 15,
    measure: 'ml',
    price: 18.78,
    category: 'roll',
    details: 'Reduces the wrinkles, increases skin firmness.',
  },
  {
    name: 'roll2',
    image: 'roll2.png',
    description: 'description',
    size: 15,
    measure: 'ml',
    price: 25.55,
    category: 'roll',
    details: 'Reduces the wrinkles, increases skin firmness.',
  },
  {
    name: 'roll3',
    image: 'roll3.png',
    description: 'description',
    size: 15,
    measure: 'ml',
    price: 12.33,
    category: 'roll',
    details: 'Reduces the wrinkles, increases skin firmness.',
  },
  {
    name: 'roll4',
    image: 'roll4.png',
    description: 'description',
    size: 15,
    measure: 'ml',
    price: 28.84,
    category: 'roll',
    details: 'Reduces the wrinkles, increases skin firmness.',
  },
];

async function seed() {
  try {
    await db.sequelize.sync({ force: true });

    await Promise.all(
      products.map((product) => {
        return db.product.create(product);
      })
    );

    console.log('Database seeded!');
    process.exit(0);
  } catch (err) {
    console.error(err);
    process.exit(1);
  }
}

seed();
